version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/" # Location of package manifests
    target-branch: "main"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub" # See documentation for possible values
    directory: "/" # Location of package manifests
    target-branch: "main"
    schedule:
      interval: "daily"
