name: esse
description: Encrypted Secure Session Engine.
author: CympleTech
homepage: https://cympletech.com
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  esse_core:
    path: ./core
  convert: any
  flutter_localizations: # localizations i18n.
    sdk: flutter
  flutter_localized_locales: any
  provider: any # state manager
  shared_preferences: any
  path_provider: any
  url_launcher: any
  permission_handler: any
  image_picker: any # pick image
  image_save: any # Mobile save image to gallery
  file_picker: any # pick file
  file_selector: any # pick file
  open_file: any # open file in mobile.
  crop: any
  unorm_dart: any
  qr_flutter: any
  qr_code_scanner: any
  web_socket_channel: any
  record: ^4.4.3
  just_audio: any
  percent_indicator: any
  bottom_navy_bar: any
  flutter_quill: any
  fluttertoast: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  integration_test:
    sdk: flutter
  flutter_launcher_icons: any #flutter pub run flutter_launcher_icons:main
  flutter_native_splash: any #flutter pub run flutter_native_splash:create
  msix: any # 1. flutter build windows 2. flutter pub run msix:create

# make windows installer.
msix_config:
  display_name: ESSE
  publisher_display_name: ESSE
  identity_name: CympleTech.com.ESSE
  msix_version: 1.0.0.0
  logo_path: .\assets\logo\esse_desktop.png
  capabilities: "internetClient,microphone,webcam"

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/logo/logo_dark.png"

flutter_native_splash:
  background_image: "assets/images/background.png"
  #android12: true

flutter:
  uses-material-design: true
  assets:
    - assets/logo/logo_dark.png
    - assets/logo/logo_light.png
    - assets/logo/logo_40.jpg
    - assets/logo/logo_chat.png
    - assets/logo/logo_jarvis.png
    - assets/logo/logo_group.png
    - assets/logo/logo_domain.png
    - assets/logo/logo_dao.png
    - assets/logo/logo_cloud.png
    - assets/logo/logo_wallet.png
    - assets/logo/logo_eth.png
    - assets/logo/logo_tether.png
    - assets/logo/logo_erc20.png
    - assets/logo/logo_nft.png
    - assets/logo/logo_btc.png
    - assets/logo/logo_esse_nft.png
    - assets/images/background_light.jpg
    - assets/images/background_dark.jpg
    - assets/images/image_missing.png
    - assets/images/file_default.png
    - assets/images/file_pdf.png
    - assets/images/file_image.png
    - assets/images/file_markdown.png
    - assets/images/file_word.png
    - assets/images/file_sheet.png
    - assets/images/file_video.png
    - assets/images/dir_folder.png
    - assets/images/dir_favorites.png
  # fonts:
  #   - family: 'Noto'
  #     fonts:
  #       - asset: assets/fonts/NotoSans-Regular.ttf # default
  #   - family: 'EmojiFont'
  #     fonts:
  #       - asset: assets/fonts/twemoji.ttf
        #- asset: assets/fonts/NotoColorEmoji.ttf
